export const FILTER = 'FILTER';
export const RECEIVE_ADDED_PRODUCT = 'RECEIVE_ADDED_PRODUCT';
export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS';
export const RECEIVE_PRODUCT_DELETED = 'RECEIVE_PRODUCT_DELETED';
export const RECEIVE_EDITED_PRODUCT = 'RECEIVE_EDITED_PRODUCT';
export const START_EDIT_MODE = 'START_EDIT_MODE';
